import { useState } from "react";
import axios from "axios";
import "./Modal.css";
import "./StudentModal.css";

const StudentModal = ({refreshStudents}) => {
  const [showModal, setShowModal] = useState(false);
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [password, setPassword] = useState("");
  const [course, setCourse] = useState("");

  const addStudentName = async () => {
    try {
      await axios.post("http://localhost:3000/students", {
        firstName,
        lastName,
        course,
        password,
      });
      setFirstName("");
      setLastName("");
      setCourse("");
      setPassword("");
      refreshStudents();
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <div className="button-row-header">
        <button onClick={() => setShowModal(true)}> + Add Student</button>
      </div>
      {showModal && (
        <div className="modal">
          <div className="modal-content">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                addStudentName();
              }}
            >
              <h2>Add Student</h2>

              <div className="name-row">
                <div className="form-group">
                  <label>First Name</label>
                  <input
                    type="text"
                    placeholder="Student First Name"
                    value={firstName}
                    onChange={(e) => {
                      const value = e.target.value;

                      if (/^[A-Za-z\s]*$/.test(value)) {
                        setFirstName(value);
                      }
                    }}
                    required
                  />
                </div>

                <div className="form-group">
                  <label>Last Name</label>
                  <input
                    type="text"
                    placeholder="Student Last Name"
                    value={lastName}
                    onChange={(e) => {
                      const value = e.target.value;

                      if (/^[A-Za-z\s]*$/.test(value)) {
                        setLastName(value);
                      }
                    }}
                    required
                  />
                </div>
              </div>

              <div className="form-group">
                <label>Course</label>

                <select
                  value={course}
                  onChange={(e) => setCourse(e.target.value)}
                  required
                >
                  <option value="">Select Course</option>
                  <option value="BSCS">BS Computer Science</option>
                  <option value="BSIT">BS Information Technology</option>
                  <option value="BSIS">BS Information Systems</option>
                  <option value="BSN">BS Nursing</option>
                </select>
              </div>

              <hr className="my-6" />
              <br />
              <p>
                The Students Username will be the ID generated by the system
              </p>

              <div className="form-group">
                <label>Password</label>
                <input
                  type="text"
                  placeholder="Student Login Password"
                  value={password}
                  onChange={(e) => {
                    const value = e.target.value;

                    setPassword(value);
                  }}
                  required
                />
              </div>

              <br />

              <div className="button-row">
                <button type="submit">Save</button>

                <button type="button" onClick={() => setShowModal(false)}>
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </>
  );
};

export default StudentModal;
